# Generated by Django 5.2.8 on 2025-11-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('completed', 'завершена')], default='created', max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.message')),
                ('recipients', models.ManyToManyField(to='clients.clients')),
            ],
        ),
    ]
