# Generated by Django 5.2.8 on 2025-11-18 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_mailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='datetime',
            new_name='datetime_end',
        ),
        migrations.AddField(
            model_name='mailing',
            name='datetime_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'успешно'), ('failed', 'неуспешно')], max_length=10)),
                ('server_response', models.TextField(blank=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mailing')),
            ],
        ),
    ]
