# Generated by Django 5.2.8 on 2025-11-20 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_datetime_mailing_datetime_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 21, 8, 41, 24, 202903, tzinfo=datetime.timezone.utc)),
        ),
    ]
