# Generated by Django 5.2.8 on 2025-11-21 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_mailing_datetime_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 22, 9, 35, 18, 619114, tzinfo=datetime.timezone.utc)),
        ),
    ]
