# Generated by Django 5.2.8 on 2025-11-25 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clients_user_mailing_user_alter_mailing_datetime_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 11, 58, 56, 891956, tzinfo=datetime.timezone.utc)),
        ),
    ]
