# Generated by Django 5.2.8 on 2025-11-25 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_mailing_datetime_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 12, 1, 57, 462367, tzinfo=datetime.timezone.utc)),
        ),
    ]
